title : ACE Automation (IaC)
author: Aviatrix Certified Engineer
copyright: '2023'
logo: 'docs/images/aviatrix-logo.png'

# Short description about the book
description: >-
  Aviatrix ACE Automation (IaC) Lab Guide

execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  home_page_in_navbar         : true
  favicon                     : 'docs/images/aviatrix-favicon-32.png'
